version: "3.8"
services:
  app:
    build: .
    container_name: golang_app
    ports:
      - "8000:8000"
  db:
    image: postgres:13.3
    environment: 
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data/