version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    # Need to create databse gowebapp1
